# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/tweet.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fsrc/tweet.proto\x12\x03\x41pp\"?\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bprofile_url\x18\x02 \x01(\t\x12\x14\n\x0c\x66ollower_ids\x18\x03 \x03(\x03\"]\n\x05Tweet\x12\x19\n\x06\x61uthor\x18\x04 \x01(\x0b\x32\t.App.User\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x11\x63reated_timestamp\x18\x02 \x01(\x03\x12\x10\n\x08mentions\x18\x05 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.tweet_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USER._serialized_start=24
  _USER._serialized_end=87
  _TWEET._serialized_start=89
  _TWEET._serialized_end=182
# @@protoc_insertion_point(module_scope)
